import type { Metadata } from 'next'
import { Inter, Press_Start_2P, VT323 } from 'next/font/google'
import Providers from './providers'
import './globals.css'
import Authprovider from './components/Auth/Authprovider'

const press_Start_2P = Press_Start_2P({ subsets: ['latin'], weight: '400', })
const vt = VT323({ subsets: ['latin'], weight: '400', })
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'AstLog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Providers>
          <Authprovider>
            {children}</Authprovider>
        </Providers>
      </body>
    </html>
  )
}
