import type { Metadata } from 'next'
import { Inter, Press_Start_2P,VT323 } from 'next/font/google'
import {QueryClientProvider,QueryClient} from '@tanstack/react-query'
import './globals.css'

const press_Start_2P = Press_Start_2P({ subsets: ['latin'],weight:'400', })
const vt = VT323({ subsets: ['latin'],weight:'400', })
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'AstLog',
  description: 'Generated by create next app',
}

const queryClient=new QueryClient()
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
      <body className={inter.className}>{children}</body>
      </QueryClientProvider>
    </html>
  )
}
